#! /usr/bin/sh

# url=$1				# 

# url=./url

usage (){
    echo "book_mile [OPTION] 
    -n \"URL\" - Add the book from Amazon link
    -l - List books 
    -h - Show this help"
    exit
}

list(){
    cat ~/bof/unix/bookmile/book_list| less
    # less ~/bof/unix/bookmile/book_list
}
while getopts lhn: OPT
do
 case $OPT in
     n) FLG_N=1 ; URL=$OPTARG
	;;
     l) list
	;;
     h) usage ;
     	;;
 esac
done; shift `expr $OPTIND - 1`

if [ -n "$FLG_N" ]; then
wget -O "/tmp/data_url" $URL
sed -e 's/|/\/\//g' /tmp/data_url >/tmp/temp_url
python3 book_info.py /tmp/temp_url >>~/bof/unix/bookmile/book_list

rm /tmp/temp_url /tmp/data_url 
fi 




