#! /usr/bin/sh
#
# Copyright (c) 2020, Keita Kitaura
# All rights reserved.
#
# $Id: $
#
# github page: https://github.com/Index700/bookmile


# url=$1				

# url=./url

usage (){
    echo "book_mile [OPTION] 
    -n \"URL\" - Add new book from Amazon link
    -l - List books 
    -h - Show this help
    
    --- Not complete --- 
    -k KEYWORD - add the book keyword
    -r NUMBUER - change status how much you read the book
    -s [paper, kindle, borrow, want] - change the book status"
   
    exit
}

list(){
    less ~/bof/unix/bookmile/book_list
}


#main
while getopts lhn: OPT
do
 case $OPT in
     n) FLG_N=1 ; URL=$OPTARG
	;;
     l) list
	;;
     h) usage ;
     	;;
 esac
done; shift `expr $OPTIND - 1`

if [ -n "$FLG_N" ]; then
wget -O "/tmp/data_url" $URL
sed -e 's/|/\/\//g' /tmp/data_url >/tmp/temp_url
python3 ~/bof/unix/bookmile/book_info.py /tmp/temp_url >>~/bof/unix/bookmile/book_list

rm /tmp/temp_url /tmp/data_url 
fi 




